project:
  type: website

website:
  title: "Spatial omics analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: software.qmd
        text: Software
      - href: examples.qmd
        text: Examples
      - href: gettingStarted.qmd
        text: Getting Started

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



