project:
  type: website

website:
  title: "SPICY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Data examples
        menu:
          - datasets/IMC_SCC.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



