project:
  type: website

website:
  title: "Spatial omics analysis"
  navbar: 
    logo: images/USydLogo.svg
#    logo-href: "https://www.sydney.edu.au/science/our-research/research-centres/sydney-precision-data-science-centre.html"
    background: "white"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: software.qmd
        text: Software
      - href: examples.qmd
        text: Examples
      - href: gettingStarted.qmd
        text: Getting Started
    

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true



