project:
  type: website

website:
  title: "SPICY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: questions.qmd
        text: "Analytical questions"
      - href: examples.qmd
        text: Examples
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



